# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 039779d51c75608a44c3f4ac465c985bc83206bd402b42260bd3f7e1df90dca13ea936d9ee5847d5ea71d6971308bd31c954c8bdc368e38a0319b168b4cb5d68

test:
  secret_key_base: 05625932723f1c02cc71eb33f657e46ba770bd89061c979689c44a78b0431acef316facf428407f8087df690e63465c466e1b5c0462f90d5f7f7955bd919a254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
